name: SDPC
version: '${project.version}'
main: skyclash.skyclash.main
softdepend: ['Multiverse-Core']
commands:
  startgame:
   description: starts game
   usage: /startgame
   permission: host
  setvotes:
   description: adjusts votes of a map
   usage: /setvotes <map index> <value>
   permission: host
   aliases: [setvote, voteset, setmapvotes]
  giveitem:
    description: gives a custom item
    usage: /giveitem <player> <item>
    aliases: [gi, customitem]
    permission: host
  endgame:
    description: manually end a game
    usage: /endgame
    aliases: [abort, end_game, shank]
    permission: host
  lootchest:
    description: set loot in chests
    usage: /lootchest <name>
    aliases: [chestloot, saveloot]
    permission: host
  lobby:
    description: go back to lobby world
    usage: /lobby
    aliases: [home, hub]
    permission: lobby
  setchest:
    description: add or remove chest location from world
    usage: /setchest [add|remove|list]
    permission: host
  gamespawn:
    description: add or remove spawn points for when games start
    usage: /gamespawn [add|remove|list]
    permission: host

permissions:
  sgm.lobby:
    description: Allows everyone to use lobby command
    default: true
  sgm.host:
    description: allows admin commands in SDPC
    default: op